13 informacje o pomieszczeniach przekraczajace wybrane progi
mati2251/building-info pull request #22
Opened 2023-12-10 12:52 UTC by DawidJedraszczyk

2023-12-11 07:39 UTC, mati2251 requested changes

2023-12-11 07:39 UTC, mati2251 commented on src/main/java/pl/put/bulidinginfo/models/RoomCompound.java
> +                    if (room.getHeatingPerCubeMeter() > thresholdRate) {
Lepiej ten warunek przenieść do Room jeśli jest spełniony to zwracać listę jedno elementową z pokojem, jeśli nie to pustą, a tutaj z kolei tylko agregować listy

2023-12-11 18:26 UTC, McQbis approved these changes

2023-12-17 11:11 UTC, mati2251 requested changes

2023-12-17 11:11 UTC, mati2251 commented on src/main/java/pl/put/bulidinginfo/models/RoomCompound.java
>              }
Teraz możemy zamiast sprawdzać czy to pietro od razu wywołać bez fora po pokojach filteredLocations.addAll(room.getLocationsWithHigherHeatingRate(thresholdRate)); 
jest to uniwersalniejsze i czytelniejsze

2023-12-17 11:51 UTC, mati2251 approved these changes

2023-12-17 13:20 UTC, merged